App\Entity\Location:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [city, country]
              message: 'This location already exists.'
              groups: ['create', 'edit']

    properties:
        city:
            - NotBlank: { groups: ['create', 'edit'] }
            - Length:
                  min: 2
                  groups: ['create', 'edit']

        country:
            - NotBlank: { groups: ['create', 'edit'] }

        latitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Range:
                  min: -90
                  max: 90
                  groups: ['create', 'edit']

        longitude:
            - NotBlank: { groups: ['create', 'edit'] }
            - Range:
                  min: -180
                  max: 180
                  groups: ['create', 'edit']
